name: nisham
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  # firebase integration
  firebase_core: ^0.5.2+1
  cloud_firestore: ^0.14.3+1

  # slidable
  flutter_slidable: ^0.5.7

  # state management
  provider: ^4.3.2+2

  nb_utils: ^4.0.6

  # sharedpreference
  shared_preferences:

  cached_network_image:
  dots_indicator: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true



  assets:
    - assets/
